#!/usr/bin/env bash
# Displays a list of currently running processes.
# Shows all processes, for all users, including those,
# which might not have a TYY.
# Display in a user-orient format
# Show process hierarchy

ps -auxf
