#!/usr/bin/env bash
# Gracefully relaods Gunicorn
# Reload no downtime and enable gunicorn to start on boot
# sudo systemctl daemon-reload
# sudo systemctl start gunicorn
# sudo systemctl enable gunicorn
# sudo systemctl status gunicorn

pgrep gunicorn | xargs kill -HUP
